//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by robot.rc
//
#define ID_ADD                          2
#define ID_EDIT                         3
#define ID_REMOVE                       4
#define ID_START                        6
#define ID_VIEW                         7
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ROBOTTYPE                   129
#define IDD_SEL_LINK_DLG                130
#define IDR_CONSTRUCT                   133
#define IDI_ML5                         137
#define IDI_RL5                         138
#define IDD_EDIT_LINK_DLG               138
#define IDI_GRIPE1                      139
#define IDD_FORMULA_DLG                 139
#define IDD_PARAMS_DLG                  140
#define IDD_OPT_DLG                     141
#define IDD_MATR_DLG                    142
#define IDD_KINDIR_DLG                  143
#define IDD_FLYEDIT_DLG                 144
#define IDD_SELECT_DLG                  146
#define IDD_KINREV_DLG                  147
#define IDD_EDITGIVEN_DLG               148
#define IDD_EDITVARS_DLG                149
#define IDD_DYN_SPEED_DLG               151
#define IDD_DERIV_MATR_DLG              152
#define ID_ANLS_DER_MATRICES            152
#define IDD_DYNDIR_DLG                  153
#define IDD_POS_DLG                     154
#define IDD_VALUE_DLG                   155
#define IDD_EDIT_POS_DLG                156
#define IDD_REV_DLG                     157
#define IDD_WIDE_VIEW                   158
#define IDD_GRAPHS_DLG                  159
#define IDD_TRAJ_DLG                    160
#define IDD_EDIT_TRAJ_DLG               161
#define IDD_INERT_MATR_DLG              162
#define IDD_DYN_ENERGY                  163
#define IDD_DYN_REV                     164
#define IDC_LINKLIST                    1000
#define IDC_LINK_ICON                   1001
#define IDC_LINK_NAME                   1002
#define IDC_LINK_TYPE                   1003
#define IDC_AXIS_X                      1004
#define IDC_AXIS_Y                      1005
#define IDC_AXIS_Z                      1006
#define IDC_AXIS_CUSTOM                 1007
#define IDC_AXIS_X_EDIT                 1008
#define IDC_AXIS_Y_EDIT                 1009
#define IDC_AXIS_Z_EDIT                 1010
#define IDC_LINK_X                      1012
#define IDC_LINK_Y                      1013
#define IDC_LINK_Z                      1014
#define IDC_LINK_AUTO                   1015
#define IDC_LINK_INDEX                  1017
#define IDC_APPLY                       1018
#define IDC_PREV                        1019
#define IDC_RENAME                      1019
#define IDC_NEXT                        1020
#define IDC_DELETE                      1020
#define IDC_B_DEL                       1021
#define IDC_FORM_EDIT                   1022
#define IDC_B_MX                        1023
#define IDC_B_MY                        1024
#define IDC_M_MIN                       1024
#define IDC_B_MZ                        1025
#define IDC_M_MAX                       1025
#define IDC_B_RX                        1026
#define IDC_M_LAB                       1026
#define IDC_B_RY                        1027
#define IDC_PARAMS                      1027
#define IDC_S_LAB                       1027
#define IDC_SPEED_LAB                   1027
#define IDC_B_RZ                        1028
#define IDC_VALUES                      1028
#define IDC_LINK_SPEED                  1028
#define IDC_S_MIN                       1028
#define IDC_OPT_PARS_USE                1029
#define IDC_S_MAX                       1029
#define IDC_OPT_PARS_BORD               1030
#define IDC_MATR                        1030
#define IDC_ACC_LAB                     1030
#define IDC_FROM                        1031
#define IDC_A_MIN                       1031
#define IDC_MEAN                        1032
#define IDC_A_MAX                       1032
#define IDC_TO                          1033
#define IDC_GIVEN                       1035
#define IDC_CURRENT                     1036
#define IDC_DEFAULT                     1037
#define IDC_EDIT                        1038
#define IDC_REMOVE                      1039
#define IDC_INSYST                      1041
#define IDC_SYST                        1042
#define IDC_REPORT                      1043
#define IDC_MOVE                        1044
#define IDC_LINK_LIST                   1045
#define IDC_MOT_STP                     1046
#define IDC_KR_PREC                     1047
#define IDC_ROT_STP                     1048
#define IDC_ADD                         1048
#define IDC_DEL                         1049
#define IDC_KR_DIVIDER                  1049
#define IDC_GRAV_X                      1050
#define IDC_PARAM                       1051
#define IDC_GRAV_Y                      1051
#define IDC_TYPE                        1052
#define IDC_GRAV_Z                      1052
#define IDC_VAL                         1054
#define IDC_PEN                         1055
#define IDC_LIST_BTN                    1057
#define IDC_VARS                        1064
#define IDC_CURR_BTN                    1065
#define IDC_VALUE                       1066
#define IDC_EDITVAR                     1068
#define IDC_FUNC                        1070
#define IDC_SOLVE                       1071
#define IDC_VIEW                        1072
#define IDC_PRG                         1074
#define IDC_ANSWER                      1075
#define IDC_DIRECT                      1077
#define IDC_KR_USE_PROBES               1078
#define IDC_SOL                         1079
#define IDC_SPIN1                       1081
#define IDC_SPIN2                       1082
#define IDC_EDIT1                       1083
#define IDC_EDIT2                       1084
#define IDC_EDIT_LINKS                  1084
#define IDC_LINK                        1085
#define IDC_COORDINATE                  1086
#define IDC_COORDINATES                 1086
#define IDC_CHECK1                      1087
#define IDC_SUBSTATE                    1087
#define IDC_POS                         1088
#define IDC_STORE                       1089
#define IDC_VEL                         1089
#define IDC_SAVE                        1090
#define IDC_ACC                         1090
#define IDC_POSITION                    1092
#define IDC_PROGRESS                    1093
#define IDC_INFO                        1094
#define IDC_GRAPH                       1095
#define IDC_POINTS                      1096
#define IDC_TIME                        1097
#define IDC_X                           1098
#define IDC_PROG                        1098
#define IDC_Y                           1099
#define IDC_TEXT                        1099
#define IDC_Z                           1100
#define IDC_LENGTH                      1100
#define IDC_RADIUS                      1101
#define IDC_MASS                        1102
#define IDC_CAPT                        1102
#define IDC_POWERS                      1103
#define ID_ADD_LINK                     32771
#define ID_VIEW_MODES_2D                32772
#define ID_VIEW_MODES_3D                32773
#define ID_EDIT_DEL                     32774
#define ID_EDIT_PROPS                   32775
#define ID_EDIT_ADD                     32779
#define ID_MAST_LESS                    32780
#define ID_MAST_MORE                    32781
#define ID_MAST_NORM                    32782
#define ID_VIEW_CENTER                  32783
#define ID_EDIT_FORMULA                 32784
#define ID_ANLS_PARAMS                  32787
#define ID_ANLS_OPTIONS                 32789
#define ID_ANLS_MATRICES                32790
#define ID_ANLS_KIN_DIR                 32791
#define ID_ANLS_KIN_REV                 32792
#define ID_VIEW_REFRESH                 32793
#define ID_EDIT_SELECT                  32794
#define ID_CTRL_MOVE_DEFAULT            32795
#define ID_CTRL_FORV                    32796
#define ID_CTRL_BACK                    32797
#define ID_EDIT_NEXT                    32798
#define ID_EDIT_PREV                    32799
#define ID_ANLS_AXIS                    32800
#define ID_ANLS_TRAJECTORY              32803
#define ID                              32804
#define ID_ANLS_MATR_INERT              32806
#define ID_Menu                         32807
#define ID_CTRL_DO_TRAJ                 32809
#define ID_ANLS_DYN_REV                 32813
#define ID_ANLS_ENERGY                  32845
#define ID_BUTTON32851                  32851
#define IDS_STRING1                     61440
#define IDS_STRING129AFX_IDS_SAVEFILE   61441
#define IDS_STRING61442                 61442

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32852
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
